some minor SBCL and Emacs changes

diff --git a/bin/common-lisp-support b/bin/common-lisp-support
--- a/bin/common-lisp-support
+++ b/bin/common-lisp-support
@@ -224,17 +224,35 @@ cvs -d :pserver:anonymous:anonymous@common-lisp.net:/project/slime/cvsroot co sl
 action_install_emacs() {
 #
 DL="${DLBASE}/gnu.org"
-EV="24.1"
+if [ -z "$1" ]
+then
+	EV="24.2"
+else
+	EV="$1"
+fi
 #
-#sudo aptitude install libgtk-3-dev libxaw7-dev libjpeg-dev libgif-dev libtiff4-dev
-#sudo aptitude install libotf-dev libm17n-dev libxml2-dev libgpm-dev libdbus-1-dev librsvg2-dev imagemagick libgconf2-dev
-# libncurses5-dev libgnutls-dev libmagickwand-dev
-tar xf "${DL}/emacs-${EV}.tar.bz2"
+#sudo apt-get install libgtk-3-dev libxaw7-dev libjpeg-dev libgif-dev libtiff4-dev
+#sudo apt-get install libotf-dev libm17n-dev libxml2-dev libgpm-dev libdbus-1-dev librsvg2-dev imagemagick libgconf2-dev
+#sudo apt-get install libncurses5-dev libgnutls-dev libmagickwand-dev
+CC=""
+for C in "xz" "bz2" "gzip"
+do
+	if [ -z "$C" ] ; then continue ; fi
+	if [ ! -f "${DL}/emacs-${EV}.tar.${C}" ] ; then continue ; fi
+	CC="$C"
+done
+if [ -z "$CC" ]
+then
+	echo "Error: failed to find emacs archive!" >&2
+	exit 1
+fi
+#tar xf "${DL}/emacs-${EV}.tar.bz2"
+tar xf "${DL}/emacs-${EV}.tar.${CC}"
 mkdir "emacs-${EV}-build"
 cd "emacs-${EV}-build"
 export LANG="C"
 ../emacs-${EV}/configure --prefix=/opt/emacs/${EV}
-make -j8 all
+make -j9 all
 make install
 cd ..
 rm -rf "emacs-${EV}*"
@@ -266,7 +284,8 @@ action_setup_quicklisp() {
 QLB="/opt/lisp/quicklisp"
 mkdir -p "${QLB}"
 cd "${QLB}"
-wget -nc -O http://beta.quicklisp.org/quicklisp.lisp
+#wget -nc -O "http://beta.quicklisp.org/quicklisp.lisp"
+curl -O http://beta.quicklisp.org/quicklisp.lisp
 QLL="quicklisp.lisp"
 if [ -f "${QLL}" ]
 then
@@ -293,7 +312,8 @@ BN=$(basename $0)
 cat <<EOF
 usage: ${BN} [ACTION]
 	ACTION: sbcl-download RELEASE | sbcl-src-install RELEASE | sbcl-git-install |
-                sbcl-slime-core       | setup-quicklisp          | help
+                sbcl-slime-core       | setup-quicklisp          | setup-emacs      |
+		help
 EOF
 }
 
@@ -305,6 +325,7 @@ cat <<EOF
 	sbcl-git-install [ sgi ]: install sbcl from git repository
 	sbcl-slime-core  [ ssc ]: generate a core for fow sbcl-slime
 	setup-quicklisp  [ sql ]: setup quicklisp
+	setup-emacs      [ se  ]: setup/install emacs
 	help             [ ?   ]: this help text
 EOF
 }
@@ -330,6 +351,9 @@ sbcl-slime-core|ssc)
 ;;
 setup-quicklisp|sql)
 	action_setup_quicklisp
+;;
+setup-emacs|se)
+	action_install_emacs "$2"
 ;;
 help|-h|--help|?)
 	action_help
