minor tweaking of gitchecker

diff --git a/bin/gitchecker b/bin/gitchecker
--- a/bin/gitchecker
+++ b/bin/gitchecker
@@ -49,6 +49,16 @@ then
 	exit 1
 fi
 
+# update from origin
+git pull "${RO}" "${BRANCH}"
+if [ "$?" != "0" ]
+then
+	echo "Error: failed to pull branch \"${BRANCH}\" from remote \"${RO}\"!" >&2
+	exit 1
+fi
+
+# update from upstream
+echo "*** ----------------------------------------------------"
 git pull "${RU}" "${BRANCH}"
 if [ "$?" != "0" ]
 then
@@ -56,6 +66,7 @@ then
 	exit 1
 fi
 
+# push to origin
 echo "*** ----------------------------------------------------"
 git push "${RO}" "${BRANCH}"
 if [ "$?" != "0" ]
