made pathes more general

diff --git a/bin/kickstart-llvm b/bin/kickstart-llvm
--- a/bin/kickstart-llvm
+++ b/bin/kickstart-llvm
@@ -3,7 +3,7 @@
 SCRIPT_NAME=$(basename $0)
 SCRIPT_PATH=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
-LLVM_SRC_BASE="/home/ADESTIS/bm/source/llvm"
+LLVM_SRC_BASE="${HOME}/source/llvm"
 LLVM_OPT_BASE="/opt/llvm"
 LLVM_OPT_PREF="${LLVM_OPT_BASE}/svn"
 
@@ -57,8 +57,15 @@ action_setup_svn() {
 
 
 action_recompile() {
+	
+	LLVM_SRC_BUILD="${LLVM_SRC_BASE}/build"
 
-	pushd "${LLVM_SRC_BASE}/build"
+	if [ ! -d "${LLVM_SRC_BUILD}" ] ; then
+		echo "Error: can not access LLVM build directory!" >&2
+		exit 1
+	fi
+
+	pushd "${LLVM_SRC_BUILD}"
 
 	nice make update && \
 		nice make -j9 all && \
